### ISSUE TITLE
Getting "CSS Modules cannot be imported from within node_modules." with 4.0.0 and next 9.5.0

### ISSUE THREAD

**Issue by EvHaus** [martpie/next-transpile-modules#95] opened 2020-07-28 03:32 UTC
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
A local package

**Describe the bug**
I'm using Yarn workspaces and CSS Modules. After upgrading from `next-transpile-modules@3.3.0` and `next@9.4.4` to `next-transpile-modules@4.0.0` and `next@9.5.0` I'm getting the following error when running my application:

```
CSS Modules cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-modules-npm
```

From reading the source code, I see that CSS Modules are detected through some hacky string parsing. Maybe it's not working after the upgrade? Rolling back resolves the issue.

**To Reproduce**

My repo structure is as follows:

```
package.json
    packages/
        packageA/
        packageB/
```

Then I import some components in `packageA` from `packageB`. Both use CSS Modules.

**Expected behavior**

No errors. Same behavior as in v3.3.0

**Setup**

- Next.js version: 9.5.0
- `next-transpile-modules` version: 4.0.0
- Node.js version: 14.0.0
- `npm`/`yarn` version: yarn@1.22.4
- Operating System: MacOS

**Comment by jackyef** [comment] 2020-07-28 05:20
I also noticed this issue happening. Seems like providing any value to the array provided to `next-transpile-modules` will cause this error to occur.

Here is a [repo](https://github.com/jackyef/next-95-tm-repro) to show the issue.
In `next.config.js`, simply changing
```
const withTM = require('next-transpile-modules')(['something']);
```
to
```
const withTM = require('next-transpile-modules')([]);
```

Will allow the project to build correctly.

**Comment by ratheo** [comment] 2020-07-28 06:34
Looks like another issue with the cssloader issuer. The error disappears when changing the issuer to this.
```
nextCssLoader.issuer = {
  or: nextCssLoader.issuer.and.concat(includes),
  not: excludes,
}
```

So that the issuer contains the path of the running application in the `or` field instead of `and`.

**Comment by martpie** [comment] 2020-07-28 06:52
Thank you lads for the report, I'll look into it as soon as possible and will try to add tests to prevent this regression from happening (but it's weird because we have a test for that, so I'll have to check what I did wrong)

**Comment by martpie** [comment] 2020-07-28 08:04
So I've just tested with this app (`basic`) and cannot reproduce this bug. Can you elaborate a bit more on what is not working, or the specificity of your setup?

**Comment by martpie** [comment] 2020-07-28 08:06
I cannot reproduce this error with my test setup here (`basic`): https://github.com/martpie/next-transpile-modules/tree/master/src/__tests__/__apps__

can you tell me more about the specificity of your setup?

**Comment by martpie** [comment] 2020-07-28 08:28
I could not reproduce it, but I could see indeed where the problem was in the webpack config, thanks for your help. I am going to draft a release, it would be great if someone can test it asap.

Also, I still could not reproduce it locally, so I have no idea how to test this scenario, all feedback is welcome.

**Comment by ratheo** [comment] 2020-07-28 08:31
With yarn workspaces, the symlinked local packages are hoisted to the root of the project, which means they don't match with the path of the running project directory.

```
node_modules
     packageA/
     packageB/
package.json
    packages/
        packageA/
        packageB/
```

Since your test project is not using yarn workspaces, the local package symlinks are placed inside the node_modules folder of your `basic` package, which means they also match with the running project directory.

**Comment by martpie** [comment] 2020-07-28 08:33
Thanks, I will add a test for yarn workspaces

**Comment by martpie** [comment] 2020-07-28 12:48
I have a potential fix available here: https://github.com/martpie/next-transpile-modules/pull/96

Would you be able to test it before I release it to tell me if it solves your problem?

**Comment by slavb18** [comment] 2020-07-28 13:20
confirm same bug with project https://github.com/slavb18/nextjscssmodules

**Comment by martpie** [comment] 2020-07-28 16:33
Should hopefully be fixed in 4.0.1, please share feedback if it works (or not)!

**Closed by martpie** 2020-07-28 16:33 UTC
Labels: bug

**Comment by EvHaus** [comment] 2020-07-29 00:57
Confirmed. 4.0.1 did the trick. Thanks for the fast turnaround!

**Comment by jackyef** [comment] 2020-07-29 02:56
4.0.1 fixed it for my as well, thanks!

**Comment by JWess** [comment] 2021-02-17 20:21
I know this issue has long been laid to rest, but I just wanted to report that I was on 4.1.0 and had to roll back to 3.3.0 to get rid of this error. I am not using any local packages. I am on NextJS 9.4.4.

**Comment by martpie** [comment] 2021-02-17 20:47
Old versions are not supported and I recommend you to update to `ntm` v6, if you have no local package the upgrade should be quite straightfoward.

**Comment by martpie** [comment] 2021-02-17 20:48
Also, see #146
