### ISSUE TITLE
ModuleNotFoundError using pnpm

### ISSUE THREAD

**Issue by elliottsj** [martpie/next-transpile-modules#36] opened 2019-05-28 19:16 UTC
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Describe the bug**
Using [pnpm](https://github.com/pnpm/pnpm)@3.4.1, this error is produced when using next-transpile-modules:

```
[ ModuleNotFoundError: Module not found: Error: Can't resolve 'object-assign' in '/Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/cjs'
    at factory.create (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/neo-async/2.6.1/node_modules/neo-async/async.js:2830:7
    at /Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/neo-async/2.6.1/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/webpack/4.29.0_webpack@4.29.0/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/tapable/1.1.3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/spencerelliott/Dev/path/to/repo/common/temp/node_modules/.registry.npmjs.org/enhanced-resolve/4.1.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'object-assign' in '/Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/cjs'
  Parsed request is a module
  using description file: /Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/package.json (relative path: ./cjs)
    resolve as module
      /Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/cjs/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/path/to/repo/packages/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/path/to/repo/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/Yolk-HQ/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/Dev/node_modules doesn't exist or is not a directory
      /Users/spencerelliott/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

This happens due to the fact that pnpm relies on symbolic links inside of `node_modules`, and next-transpile-modules disables webpack's resolution of symlinks:

https://github.com/martpie/next-transpile-modules/blob/0e76c25528d961ad1843ccdddf3de0e77e9ff9aa/index.js#L46

**To Reproduce**
Set up a new project using pnpm@3.4.1, next@8.0.4, and next-transpile-modules@2.3.1. Run `next dev` and observe the error above.

Minimal reproduction: https://github.com/elliottsj/next-transpile-modules-issue-36

**Expected behavior**
The above error does not occur, and the application starts normally.

**Setup**

- Next.js version: 8.0.4
- `next-transpile-modules` version: 2.3.1
- Node.js version: 10.15.0
- `npm` version: N/A
- Operating System: macOS

**Comment by martpie** [comment] 2019-05-28 19:19
I never used `pnpm`, maybe we can add an option to disable the symlinks, I'll have a look.

Can you tell me how to reproduce it easily?

**Comment by elliottsj** [comment] 2019-05-28 19:38
Sure, I've created a minimal repro here: https://github.com/elliottsj/next-transpile-modules-issue-36

**Comment by martpie** [comment] 2019-06-17 09:35
@elliottsj I have a question

> This happens due to the fact that pnpm relies on symbolic links inside of node_modules, and next-transpile-modules disables webpack's resolution of symlinks:

We use `config.resolve.symlinks = false;` to avoid Webpack resolving symlinks to their realpath.

Here is an example of `node_modules` in one of my project:

```
...
lrwxr-xr-x    1 pierre  staff     16 Jun 14 11:03 styleguide -> ../../styleguide
...
```

The problem is if I `config.resolve.symlinks = true;`, Webpack will resolve symlinks to the relative path (`../../styleguide/components/Button` for example), and the file being out of the Next.js directory, Next.js won't transpile it properly. But by keeping this symlinks option, the `styleguide` is "in the same directory" because it's in `node_modules/`.

Could you detail me more how pnpm works?

ps: if importing files from outside Next.js directory is now supported (I remember Tim Neutkens telling me about it for the next major version as a potential feature), then I guess we could remove this option.

**Comment by elliottsj** [comment] 2019-06-19 18:53
This is a good summary of how it works: https://pnpm.js.org/docs/en/symlinked-node-modules-structure.html

Given the `Module not found: Error: Can't resolve 'object-assign'` error above, this means that webpack is trying to resolve 'object-assign' relative to the directory `/Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/cjs`.

However, this is the pnpm structure on disk:

```
$ pwd
/Users/spencerelliott/Dev/path/to/repo/packages/login-web
$ cd node_modules/react-dom/
$ pwd
/Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/.registry.npmjs.org/react-dom/16.8.6_react@16.8.6/node_modules/react-dom
$ ls -l ..
total 0
lrwxr-xr-x   1 spencerelliott  staff   53 Jun 18 16:44 loose-envify -> ../../../loose-envify/1.4.0/node_modules/loose-envify
lrwxr-xr-x   1 spencerelliott  staff   55 Jun 18 16:44 object-assign -> ../../../object-assign/4.1.1/node_modules/object-assign
lrwxr-xr-x   1 spencerelliott  staff   50 Jun 18 16:44 prop-types -> ../../../prop-types/15.7.2/node_modules/prop-types
lrwxr-xr-x   1 spencerelliott  staff   40 Jun 18 16:44 react -> ../../../react/16.8.6/node_modules/react
drwxr-xr-x  19 spencerelliott  staff  608 Jun 18 16:44 react-dom
lrwxr-xr-x   1 spencerelliott  staff   48 Jun 18 16:44 scheduler -> ../../../scheduler/0.13.6/node_modules/scheduler
$ cd ../object-assign/
$ pwd
/Users/spencerelliott/Dev/Yolk-HQ/yolkjs/common/temp/node_modules/.registry.npmjs.org/object-assign/4.1.1/node_modules/object-assign
```

The `object-assign` package is located at `/Users/spencerelliott/Dev/Yolk-HQ/yolkjs/common/temp/node_modules/.registry.npmjs.org/object-assign/4.1.1/node_modules/object-assign`, which webpack cannot find when it tries to resolve it starting at `/Users/spencerelliott/Dev/path/to/repo/packages/login-web/node_modules/react-dom/cjs`.

**Comment by martpie** [comment] 2020-11-04 17:51
I've added integration tests for pnpm 5 and everything is passing fine, so I guess this can be closed.

If the issue is still present, please submit a failing test 🙏

**Closed by martpie** 2020-11-04 17:51 UTC
