### ISSUE TITLE
Fast refresh on changes to files in yarn workspace package stopped working in 9.5.0/4.0.0

### ISSUE THREAD

**Issue by dminkovsky** [martpie/next-transpile-modules#97] opened 2020-07-28 16:17 UTC
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**

local

**Describe the bug**

Posted originally to https://github.com/vercel/next.js/issues/15582

My next.config.js looks like this:

<details>

```
/* global __dirname */

const path = require('path');
const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules')(['pony-common']); //  <-- workspace package depended on

module.exports = withPlugins([withTM], {
    webpack: config => {
        const nextBabelLoader = findNextBabelLoader(config);
        // Set Babel root to workspace root, so config
        // applies to workspace modules.
        nextBabelLoader.options.root = resolve('..');
        // But use the local config
        nextBabelLoader.options.configFile = resolve('.babelrc');
        return config;
    },
});

function resolve() {
    return path.resolve.apply(path, [__dirname, ...arguments]);
}

// https://github.com/vercel/next.js/issues/13980#issuecomment-641955521
function findNextBabelLoader(config) {
    for (const rule of config.module.rules) {
        if (
            rule.use &&
            rule.use.loader === 'next-babel-loader'
        ) {
            return rule.use;
        } else if (
            rule.use &&
            Array.isArray(rule.use) &&
            rule.use[1].loader === 'next-babel-loader'
        ) {
            return rule.use[1];
        }
    }
    throw new Error('`next-babel-loader` not found');
}
```

</details>

I am using a monorepo Yarn workspaces layout wherein my Next.js project has a dependency on another package in my workspace.

Up to and including 9.4.4, when I changed something in the depended package, the Next.js dev server would detect that change and fast refresh.

In 9.5, this no longer works.

**To Reproduce**

Save a file in depended upon workspace package. See next dev server not detect change.

**Expected behavior**

next dev server detects change.

**Setup**
- Next.js version: 9.5.0
- `next-transpile-modules` version: 4.0.0/4.0.1
- Node.js version: 12.16.3
- `npm`/`yarn` version: yarn 1.22.4
- Operating System: macOS 10.15.4
- Webpack 4 or 5: 4

**Additional context**

None

**Comment by martpie** [comment] 2020-07-28 16:31
Can you try 4.0.1 and tell me if it was fixed?

**Comment by martpie** [comment] 2020-07-28 16:39
Also, please use the full template when reporting bugs.

**Comment by dminkovsky** [comment] 2020-07-28 17:07
> Can you try 4.0.1 and tell me if it was fixed?

No effect 

> Also, please use the full template when reporting bugs.

Updated

**Comment by dminkovsky** [comment] 2020-07-28 20:04
Thanks @martpie. Please let me know if you have any issues replicating easily. I am assuming you have some yarn workspaces repo that looks like this? If not, I'll try to put together a repo.

@michaelbirchler are you experiencing this too?

**Comment by martpie** [comment] 2020-07-28 20:06
If someone cannot wait, feel free to submit a PR, I won't work on it before tomorrow (it's 10pm right now, western Europe time) ;)

**Comment by dminkovsky** [comment] 2020-07-28 20:11
Definitely no rush for me at all...

вт, 28 июля 2020 г. в 16:07, Pierre de la Martinière <
notifications@github.com>:

**Comment by michaelbirchler** [comment] 2020-07-28 22:35
>@michaelbirchler I see you thumbs-uped. Are you experiencing this too?

@dminkovsky yes, I'm experiencing the same behavior within a yarn workspaces repository.

**Comment by aleksei-savitski-softswiss** [comment] 2020-07-29 11:37
I'm experiencing the same issue. Fast refresh stopped working with yarn workspaces after I updated to next.js 9.5.0 and next-transpile-modules 4.0.1. 

I found the reason is here https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js#L181.
It expects that content of config.watchOptions.ignored array is regExp's but there are strings with [anymatch](https://github.com/micromatch/anymatch) patterns: `['**/.git/**', '**/node_modules/**', '**/.next/**']`.

**Comment by martpie** [comment] 2020-07-29 12:08
Should be fixed in 4.0.2, thank you very much @aleksei-savitski-softswiss 

I will try to add tests to prevent hot reloading regressions

**Closed by martpie** 2020-07-29 12:08 UTC
Labels: bug

**Comment by aleksei-savitski-softswiss** [comment] 2020-07-29 12:20
@martpie thanks for releasing it so fast! I already upgraded to 4.0.2 and it works!

**Comment by dminkovsky** [comment] 2020-07-29 14:23
Same here. Thanks everybody!

**Comment by nandorojo** [comment] 2020-11-02 23:58
I'm seeing this issue with `4.1.0` and `next` 10, is there anyone I should try besides upgrading?

**Comment by nandorojo** [comment] 2020-11-03 00:31
It seems like the problem might be coming from Webpack 5. I don't know my way around Webpack at all, but I'll mention here if I find a solution.
