### ISSUE TITLE
baseUrl doesn't work within transpiled repo

### ISSUE THREAD

**Issue by saiichihashimoto** [martpie/next-transpile-modules#154] opened 2020-12-30 21:18 UTC
- [X] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [X] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
npm package (a github dependency)

**Describe the bug**
Using [`baseUrl`](https://nextjs.org/docs/advanced-features/module-path-aliases) to have absolute imports doesn't work within the transpiled repo.

**To Reproduce**
1. Repo A is a Next.js Repo
2. Repo B is a Next.js Repo
3. Repo A & Repo B use [`baseUrl`](https://nextjs.org/docs/advanced-features/module-path-aliases) to have absolute imports.
4. In Repo A, import a component in Repo B that uses an absolute import and you receive an error.

**Expected behavior**
It should not break. 😇

**Setup**

- Next.js version: 10.0.4
- `next-transpile-modules` version: 6.0.0
- Node.js version: 12.20.0
- `npm`/`yarn` version: 6.14.8
- Operating System: OS X 10.15.6
- Webpack 4 or 5: 4.44.1

**Comment by martpie** [comment] 2020-12-30 21:42
Never tried this feature, I'll have to have a look :)

**Comment by fabian-hiller** [comment] 2021-01-04 15:13
@martpie Is there any news on this? I have the same problem in a monorepo, when importing a local package into a Next.js app, which uses "baseUrl" for absolute paths within the local package.

**Comment by martpie** [comment] 2021-01-04 15:16
I did not have a look yet, I'm onto various other things right now and I cannot guarantee an ETA. Feel free to investigate and submit a PR and I will find the time to review it 👍

**Comment by fabian-hiller** [comment] 2021-01-04 15:55
@martpie Here is a simple example repo: https://github.com/fabian-hiller/monorepo-typescript-next-the-sane-way. I also took a look at the `next-transpile-modules.js` file and I'm not sure if it's even possible to solve the problem.

**Comment by martpie** [comment] 2021-01-04 16:03
I don't see any custom path configuration in this repo 🤔

**Comment by fabian-hiller** [comment] 2021-01-04 16:10
@martpie In the `tsconfig.js` of the `/shared` directory `baseUrl` is set to `.`, which allows absolute paths within the directory. If absolute paths are used, for example in the `/shared/utils/calc.ts` file, the app will no longer work in the `/website` directory, because the absolute paths cannot be resolved there.

**Comment by fabian-hiller** [comment] 2021-01-04 16:14
Is it possible that **next-transpile-modules** resolves these paths in advance and changes them e.g. to relative paths?

**Comment by martpie** [comment] 2021-01-04 16:19
Ah, I see, I understand better the issue. Out of curiosity, could you try to configure it so it adds something before the name of the package?

```diff
-export { add } from 'utils/add';
+export { add } from '~utils/add';
```

(for example)

I guess it could be solvable by a custom resolver 🤔 but it would start adding quite a bit of logic to handle these cases, I have to do some research.

**Comment by fabian-hiller** [comment] 2021-01-04 16:27
> Out of curiosity, could you try to configure it so it adds something before the name of the package?

Yes I can change that.

I don't know if it helps, in another project we had used "@zerollup/ts-transform-paths" to change absolute paths to relative ones. Maybe it serves for inspiration.

**Comment by martpie** [comment] 2021-01-04 16:46
Basically, the problem is the following: 

- Webpack looks for `shared/calc`
- It finds it
- It tries to look for `calc/add`
- Webpack uses `enhanced-resolve` (I believe) which probably does not support lookups for `tsconfig`'s `baseUrl`
- x_x

So this is most probably a Webpack's `resolve` issue. That could probably be patched in this plugin, but I'm still looking for a quick and easy way.

**Comment by fabian-hiller** [comment] 2021-01-04 20:56
@martpie I found a solution with `tsconfig-paths-webpack-plugin`.

```js
// next.config.js

const { join } = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

const workspace = join(__dirname, '..');

module.exports = {
  webpack: (config, options) => {
    config.resolve.plugins = [
      ...config.resolve.plugins,
      new TsconfigPathsPlugin({ configFile: '../local-package/tsconfig.json' }),
    ];
    config.module.rules = [
      ...config.module.rules,
      {
        test: /\.(js|jsx|ts|tsx)$/,
        include: [workspace],
        exclude: /node_modules/,
        use: options.defaultLoaders.babel,
      },
    ];
    return config;
  },
};
```

Nevertheless, in the end I decided to change the absolute paths to relative ones, because more problems followed. Thanks for your quick answers.

**Comment by martpie** [comment] 2021-01-04 21:01
This is why I don't use them, it's always a nightmare to get everything right between eslint, TSC, Webpack, Babel... 😄 

In the end, relative imports are fine (imho).

I will close this, I don't think I will do anything on ntm side, unless there is a big demand from others. 👍

**Closed by martpie** 2021-01-04 21:01 UTC

**Comment by saiichihashimoto** [comment] 2021-01-05 17:14
I think it's worth adding into the README that ntm does not have baseUrl support. When deciding to use this repo, I looked at its restrictions and support to make sure I can use it so it would be good to rule it out up front.

**Comment by martpie** [comment] 2021-01-05 17:45
Good point 👍 I'll add that to the readme

**Comment by fabien** [comment] 2021-07-16 09:30
@martpie I'm not sure I'm having the same issue, but it appears to be related. Did you ever clarify this in the readme?

I'm using aliases in my `tsconfig.json` file from the main project repo:

```json
"compilerOptions": {
  "allowJs": true,
  "outDir": "./dist",
  "baseUrl": ".",
  "paths": {
    "@root/*": [
      "./*"
    ],
    "@app/*": [
      "./src/*"
    ]
  }
}
```

Then, from my dependencies I sometimes refer to a config file in my main app, like this: `import config from `@app/config/app` which works fine in my NPM 7 monorepo. There's quite a few places where I am using this construct, and I also have some cross-dependency aliases setup like that.

However, I just published my dependencies to NPM (non-transpiled) and installed the project independent from my monorepo somewhere, and now those dependencies are not being resolved:

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@app/translations'
```
I don't see what the difference between the monorepo and the independent install would be, from the perspective of transpilation and handling of `tsconfig.json` aliases. Do you have any pointers, perhaps?

I tried @fabian-hiller 's solution, but I'm fighting with `next-compose-plugins` masking the webpack config function (it's not being called).

**Comment by fabien** [comment] 2021-07-16 14:27
As a follow-up, perhaps this will help someone:

Since the dependencies are symlinked to `node_modules` within the monorepo, it masks the fact that they will be skipped by Next.js's resolver: https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack/plugins/jsconfig-paths-plugin.ts#L168

Because the resolved path will not include `node_modules` in its name, it will not be skipped while development takes place within the monorepo. However, standalone, with those dependencies being pulled in by npm from the registry, the paths will actually contain the string `node_modules` and will be skipped, thus causing all kinds of missing dependencies.

I could observe this behavior easily using `DEBUG=next:jsconfig-paths-plugin npm run build`.

My solution/workaround is to mimic the behavior of the included `JsConfigPathsPlugin` and leave out the `node_modules` check. I am replacing the standard plugin instance with my copy when the Next.js plugin is initialized.

**Comment by amlcodes** [comment] 2022-01-11 12:47
@martpie  oops, ofc, odd that im running into this. Nextjs' externalDir should be taking care of me.
